language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

notifications:
  email: false
  irc: false

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS='--show-diff' LDFLAGS="-lgcov" CFLAGS="-Wall -coverage -O0" EXTRA_LDFLAGS="-precious-files-regex .libs/msgpack.gcno"

before_script:
  - phpize
  - ./configure
  - make

script:
  - make test
  - gcov --object-directory .libs *.c
  - bash <(curl -s https://codecov.io/bash)
